### ISSUE TITLE
Upgrade to v2 causes etc.hmacSha256Sync not set

### ISSUE THREAD

**Issue by radicleart** [paulmillr/noble-secp256k1#110]
Just updated from `"@noble/secp256k1": "^1.7.0",` to `"@noble/secp256k1": "^2.0.0",`

Node: v19.8.0

This used to work

```
await secp.sign(sha256(script), privKey);
```

but in v2 throws: `Error: etc.hmacSha256Sync not set`?

**Comment by paulmillr** [comment]
take a look at upgrading in the readme before opening these issues
