### ISSUE TITLE
How do I initialize a Signature with the v2?

### ISSUE THREAD

**Issue by HRK44** [paulmillr/noble-secp256k1#111]
I have a signature without having the private key - and I want to verify that it was signed by the public key that claims the signature.
I used to do : `recoverPublicKey(msg, sig, rec)` but now it has changed to `sig.recoverPublicKey(msg)`.

How do I initialize the `Signature` since it seems that constructor only takes 2 big ints as params (and not a buffer/string).

**Comment by paulmillr** [comment]
`Signature.fromCompact(signatureHex).addRecoveryBit(rec).recoverPublicKey()`

**Comment by HRK44** [comment]
Ok thanks @paulmillr,

Could I just do:

```
    const msgHash = bip0322Hash(message);
    const signature = secp.etc.hexToBytes(signatureStr);
    const publicKey = secp.etc.hexToBytes(publicKeyStr);
    const msgHash2 = secp.etc.hexToBytes(msgHash);

    const isValid = secp.verify(signature, msgHash2, publicKey);
``` ?

**Comment by paulmillr** [comment]
There is no need to convert from hex to bytes, you can just pass hex.
