### ISSUE TITLE
why secp256k1.utils.randomPrivateKey() produce a 32 bytes key?

### ISSUE THREAD

**Issue by zzzh** [paulmillr/noble-secp256k1#116]
And so do the secp256k1.getPublicKey().
Shouldn't they produce keys of 64 bytes?

BTW: I tried it in noble/curves, guess it's the same here.

**Comment by paulmillr** [comment]
Because keys are 32 byte, not 64.

**Comment by zzzh** [comment]
I see, for my case, I need 64 bytes of the uncompressed public key to talk to another program that uses another library in another language..
 So, is there a way in this lib to uncompress it?
