### ISSUE TITLE
How to encrypt a messege (in bytes) provided that a public key from backend?

### ISSUE THREAD

**Issue by Zhaoxun** [paulmillr/noble-secp256k1#119]
Hi Paul! Thank you for the hard work of compressing secp256k1 to 4KB, which is good to run on a browser.

I want to build a point-to-point encryption from client to the last back-end server. Since ECDH provides a way that the last backend server can generate a key-pair and send only the public key to client, it would be secure that the client encrypt the request with private information by the public key to the back-end without leakage in between. 

Some ECDH programmers provide such functionality to encrypt with only a public-key:
https://pypi.org/project/eciespy/

However, we still lack a package to encrypt on the client's browser without knowing the private-key.
Of course, if the backend server generates the public key in byte form, it is easy to deliver it through Hex and translate it back to bytes in Javascript:

```
 function Hex2Bytes(hexString) {
    if ( hexString.length%2 >0) hexString='0'+hexString;
    let bt = new Uint8Array(hexString.length/2);
    for (var i=0; i<hexString.length; i+=2){
        bt[i/2] = parseInt(hexString.slice(i,i+2));
    }
    return  bt};

const Byte2Hex = (bytes) =>
  bytes.reduce((str, byte) => str + byte.toString(16).padStart(2, '0'), '');
```

Thanks in advance!

**Comment by paulmillr** [comment]
https://github.com/ecies/js
