### ISSUE TITLE
Not a bug, thanks for this project

### ISSUE THREAD

**Issue by vae520283995** [paulmillr/noble-secp256k1#12]
Thank you for this project, thank you for your post, but I don’t know much about wNAF and Endomorphism, I hope the author can post a post to talk about it in detail, thank you

**Comment by paulmillr** [comment]
What specifically are you looking to learn from? A combination of wNAF and endomorphism? Or these things in separate?

**Comment by vae520283995** [comment]
Thank you for your reply. I use java. I want to implement a java version of secp256k1 through your post. I have now completed Jacobi, but I can’t complete the following wNAF and endomorphism because I don’t understand the principles inside.
By the way, another question, I use BigInteger.modInverse in java to be faster than your egcd, I don’t know why, thank you

**Comment by paulmillr** [comment]
Endomorphism is described here https://gist.github.com/paulmillr/eb670806793e84df628a7c434a873066

I've added `USE_ENDOMORPHISM` option, but it's actually always enabled right now. It can be false only if you manually set it to false.

You have two options:

1. Use code without endomorphism. Just copy everything inside `if`s like `if (!USE_ENDOMORPHISM)`
2. Use code with endomorphism. Just copy everything from cases like `if (USE_ENDOMORPHISM)`

So, if you don't want to use endo, your `multiplyUnsafe` would look like this:

```typescript
    if (typeof scalar !== 'number' && typeof scalar !== 'bigint') {
      throw new TypeError('Point#multiply: expected number or bigint');
    }
    let n = mod(BigInt(scalar), CURVE.n);
    if (n <= 0) {
      throw new Error('Point#multiply: invalid scalar, expected positive integer');
    }
    let p = JacobianPoint.ZERO;
    let d: JacobianPoint = this;
    while (n > 0n) {
      if (n & 1n) p = p.add(d);
      d = d.double();
      n >>= 1n;
    }
    return p;
```

**Comment by vae520283995** [comment]
Thank you, I will read the description of Endomorphism carefully, can you give me some information about wNAF

**Comment by paulmillr** [comment]
It's described in wiki: https://en.wikipedia.org/wiki/Elliptic_curve_point_multiplication#w-ary_non-adjacent_form_(wNAF)_method

Basically you pre-calculate values of base point multiplied by all values from 0 to 256*16. Result of this pre-calculation is 65535 points that are later simply added between each other.

**Comment by vae520283995** [comment]
thanks
