### ISSUE TITLE
A given point validity should be tested against existence

### ISSUE THREAD

**Issue by GregTonoski** [paulmillr/noble-secp256k1#127]
https://github.com/paulmillr/noble-secp256k1/blob/90867ff49fd760d7677467d23a464e55610459a4/index.js#L143

It seems that there is the check missing: `y = ±c(p+1)/4 mod p` to the power of 2 should equal `crv(x)`. See also: https://github.com/bitcoin/bips/blob/40e91fdb94481fd3705d1426d7f20191c6b89a35/bip-0340/reference.py#L75C4-L75C35 and https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#cite_note-10.

**Comment by paulmillr** [comment]
Square root computation is done inside of fromHex. 

https://github.com/paulmillr/noble-secp256k1/blob/90867ff49fd760d7677467d23a464e55610459a4/index.js#L203

Bip340 which you mention is different from ECDSA. In ecdsa, there is parity bit, so, points are 33-byte (02 + point or 03 + point). In bip, the parity bit is calculated automatically.

**Comment by GregTonoski** [comment]
I think we don't understand each other. This issue is about additional check beside square root and parity bit.

**Comment by paulmillr** [comment]
The check is done inside of sqrt.

https://github.com/paulmillr/noble-secp256k1/blob/90867ff49fd760d7677467d23a464e55610459a4/index.ts#L171

**Comment by GregTonoski** [comment]
Indeed, there is the check. I overlooked that, apologies.

**Comment by paulmillr** [comment]
I've tried to make the code very short and documented, and still fit into 4KB, let me know how this can be improved.
