### ISSUE TITLE
Creating a private key deterministically?

### ISSUE THREAD

**Issue by julien51** [paulmillr/noble-secp256k1#13]
I looked for it but it appears that this library does not provide a way to generate a private key deterministically from a secret or seed. Is there anything you'd recommend using for this?

**Comment by paulmillr** [comment]
That depends on your likings.

There is BIP39 standard. For example, its js library allows to convert mnemonic phrase to private key. Or, instead, you could use `scrypt` with N=16 to convert password into private key. Which is probably simpler.

User input needs to be processed and stretched into entropy bytes, and Scrypt works good here.

**Comment by paulmillr** [comment]
Sample code:

```js
const secp = require("noble-secp256k1");
const scrypt = require('scrypt-async-js');

let key = undefined;
scrypt('password', 'salt', {N: 2 ** 16, r: 8, p: 1, dkLen: 16, encoding: 'hex'}, (_key) => {
    key = _key;
});

secp.getPublicKey(key);
```

**Comment by julien51** [comment]
Great! Thanks lot!
Closing now :)
