### ISSUE TITLE
Is it possible to add add_mixed

### ISSUE THREAD

**Issue by vae520283995** [paulmillr/noble-secp256k1#14]
https://eprint.iacr.org/2015/1060 Algorithm 8
or
http://hyperelliptic.org/EFD/g1p/data/shortw/jacobian-0/addition/madd-2007-bl

**Comment by paulmillr** [comment]
I assume this is the duplicate of #5. Why do you need it?

**Comment by vae520283995** [comment]
> I assume this is the duplicate of #5. Why do you need it?

Not the same, add_mixed is z2=1, so the speed should be slightly improved

**Comment by paulmillr** [comment]
Yeah, would be good to try. Feel free to implement it.

**Comment by vae520283995** [comment]
> Yeah, would be good to try. Feel free to implement it.

Looking forward to it soon
