### ISSUE TITLE
Questions and thanks

### ISSUE THREAD

**Issue by aulneau** [paulmillr/noble-secp256k1#17]
Hi there!

First off wanted to say thank you for your work on this, I think this is a fantastic endeavor!

( please forgive my ignorance when it comes to cryptography -- much of my time is spent as a frontend engineer :~) )

I work at Hiro systems PBC (building tools for the Stacks blockchain) and I really want to build alternatives to our libraries that depend on elliptic. I have a [semi-working implementation here](https://github.com/aulneau/stacks-crypto/tree/feat/token-signer-base58), but I am having a bit of a hard time getting a compatibility layer going between our other libraries that use elliptic. Here is an example of something I don't know how to replicate with your library:

```ts
  const ecPK = ecurve.keyFromPublic(publicKey, 'hex').getPublic();
  const ephemeralSK = ecurve.genKeyPair();
  const ephemeralPK = Buffer.from(ephemeralSK.getPublic().encodeCompressed());
  const sharedSecret = ephemeralSK.derive(ecPK) as BN;
  ```
([taken from these lines](https://github.com/blockstack/stacks.js/blob/master/packages/encryption/src/ec.ts#L266-L271))

From debugging and trying to understand the differences, I think there are issues around how elliptic uses/expects data to be in a Point format, or a BigInt. I'm wondering if you might be interested in giving an example of how to take something from `noble-secp256k1` and decrypt it with `elliptic`? [Here is a test that I would love to get passing](https://github.com/aulneau/stacks-crypto/blob/feat/token-signer-base58/tests/legacy-compat.test.ts).

Any help or guidance would be greatly appreciated!

**Comment by paulmillr** [comment]
Thanks for thanks.

Check out readme — noble-secp has [getSharedSecret](https://github.com/paulmillr/noble-secp256k1#getsharedsecretprivatekeya-publickeyb). So it's `getSharedSecret(utils.randomPrivateKey(), ecPK)`
