### ISSUE TITLE
double Jacobian

### ISSUE THREAD

**Issue by Uzlopak** [paulmillr/noble-secp256k1#21]
Maybe you can shave some yoctoseconds off...

`const D = 2n * ((X1 + B) ** 2n - A - C);`

can be simplified to

`const D = 4n * X1 * B;`

**Comment by Uzlopak** [comment]
I mean we trade one power, one multiplication and one addition and two subtractions with two multiplications. 

But I think that the power operation is atleast heavy or not heavier as a multiplication. So I assume it should be some yoctoseconds faster.

**Comment by Uzlopak** [comment]
I wrote an E-Mail to Tanja Lange from https://www.hyperelliptic.org/ and asked if this simplification is valid and if what the actual cost of this modified formula is.

**Comment by Uzlopak** [comment]
I analyzed further. Seems like that this is the same as in dbl-1998-cmo-2. There the variable D is called S. So technically it is the same. But I guess we make here the classical memory vs. computational power tradeoff.

**Comment by paulmillr** [comment]
Thanks for digging into this!
