### ISSUE TITLE
publish to deno

### ISSUE THREAD

**Issue by aulneau** [paulmillr/noble-secp256k1#22]
Hi there!

Seems like there is a version on deno, https://deno.land/x/secp256k1@1.0.5, but it's out of date. can you publish the latest?

**Comment by paulmillr** [comment]
How? Seems like they should update it

**Comment by aulneau** [comment]
![Screen Shot 2021-07-20 at 5 53 50 PM](https://user-images.githubusercontent.com/11803153/126405405-b12ada24-7950-4290-b086-9a694deea0d2.png)

Maybe the webhook is disabled?

**Comment by aulneau** [comment]
Or perhaps someone just forked it, and set it up if you didn't, which would mean you'd have to publish it yourself by going to https://deno.land/x and following the steps after hitting "publish a module". at which point it will automatically update whenever you do a new release

**Comment by paulmillr** [comment]
i've added the webhook

**Comment by aulneau** [comment]
awesome! thanks @paulmillr, hopefully it'll update on the next tag 👍

**Comment by paulmillr** [comment]
It's live now
