### ISSUE TITLE
Clarify whether the library is supported in React Native

### ISSUE THREAD

**Issue by dspinellis** [paulmillr/noble-secp256k1#26]
This very promising library's [npm name](https://www.npmjs.com/package/react-native-elliptic-curve-cryptography) seems to suggest that this is a React Native library.  However, React Native currently doesn't natively support `BigInt` nor the `n` number suffix required for the library to work. These issues could be addressed using the `big-integer` package and the `@babel/plugin-syntax-bigint` plugin. I suggest either documenting the React Native library installation procedure or clarifying that the words *react native* in the library's title don't refer to React Native.

**Comment by paulmillr** [comment]
> clarifying that the words react native in the library's title don't refer to React Native

Which words? We don't have any "react" mention anywhere.

**Comment by paulmillr** [comment]
I don't know whose package is `react-native-elliptic-curve-cryptography`, it's not mine. So, you should report the issue to pkg author.

**Comment by dspinellis** [comment]
Someone appears to be pointing the [react-native-elliptic-curve-cryptography npm package](https://www.npmjs.com/package/react-native-elliptic-curve-cryptography) to this repository and your [corresponding blog post](https://paulmillr.com/posts/noble-secp256k1-fast-ecc/).  I (it turns out wrongly) assumed it was you.  Apologies for bothering you.

**Comment by uidevkarthick** [comment]
> I don't know whose package is `react-native-elliptic-curve-cryptography`, it's not mine. So, you should report the issue to pkg author.

have you reported this issue on the NPM website...?
