### ISSUE TITLE
Implement Schnorr batch verification

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/noble-secp256k1#41]
[BIP340 section](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#batch-verification)

https://gist.github.com/lontivero/1d75b11e9243c0f2a75466db05776623

**Comment by kcmed420** [comment]
> [BIP340 section](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#batch-verification)
> 
> 
> 
> https://gist.github.com/lontivero/1d75b11e9243c0f2a75466db05776623

**Comment by paulmillr** [comment]
=> noble-curves
