### ISSUE TITLE
utils.hashToPrivateKey() not available

### ISSUE THREAD

**Issue by vinliao** [paulmillr/noble-secp256k1#45]
Hi. `hashToPrivateKey()` doesn't seem to be available to me (`TypeError: secp.utils.hashToPrivateKey is not a function`). I'm using version `1.5.2`. This is not a big issue because `sign()` actually takes hexstring as an input.

I checked `index.ts` and `hashToPrivateKey()` is actually there. Am I uninstalling it incorrectly?

**Comment by paulmillr** [comment]
Hi, it's not yet available in 15.2, only github

**Comment by vinliao** [comment]
Thanks!
