### ISSUE TITLE
Might be worth committing build products

### ISSUE THREAD

**Issue by brandonblack** [paulmillr/noble-secp256k1#51]
Arguments in favor of committing build products:
* Puts a PGP signature on the build products that can be matched against published artifacts
* Allows depending on github versions directly
* Easier direct audit of the code that will actually be provided to the runtime for execution

See https://github.com/bitcoinjs/bitcoinjs-lib for an example of a project that checks in the build products.

**Comment by paulmillr** [comment]
So we have `build/noble-secp256k1.js` and `lib/index.js`, `lib/esm/index.js`. What would be the most useful to expose?

**Comment by brandonblack** [comment]
I believe committing `lib/index.js` and `lib/esm/index.js` both would let all npm/yarn users add a git version directly to their package.json and not have to wait for releases.

I've just been checking all three in over here https://github.com/brandonblack/noble-secp256k1/commit/856129c06436fb696bab7d827edad5effdffaee2 on top of your latest to facilitate development.

Over in bitcoinjs-lib land, they have a CI step that ensures that after running the build again on the CI, the build products exactly match those that are checked in.

**Comment by paulmillr** [comment]
will be in v2.0
