### ISSUE TITLE
Assert validity incorrect

### ISSUE THREAD

**Issue by gabriel-barrett** [paulmillr/noble-secp256k1#6]
The function `assertValidity()` will accept points satisfying either the equation "y² = x³ + ax +b" or the equation "-y² = x³ + ax +b". For instance, the function will accept the point 
```
let x = mod(-2n);
let y = mod(-1n);
let point = new Point(x, y);
point.assertValidity();
```
even though it's clearly not in the curve, as shown by the results of `mod(y**2n)` and `weistrass(x)`, respectively equal to `1n` and `mod(-1n)`.

**Comment by paulmillr** [comment]
Thanks. How do you think we should fix this?
