### ISSUE TITLE
Uncaught TypeError: can't convert BigInt to number

### ISSUE THREAD

**Issue by danfinlay** [paulmillr/noble-secp256k1#64]
I've got both Firefox and Chrome blowing up once I build a production react build with this library.

[this line](https://github.com/paulmillr/noble-secp256k1/blob/9e1353def2be5ee7a0a87b515a66382acb547716/index.ts#L16) throws this error:
`Uncaught TypeError: can't convert BigInt to number`

What's weird is it doesn't throw this error in development, which makes me think there's some build problem happening...

**Comment by danfinlay** [comment]
You can see this error in action at https://mobymask.com/, it'll probably be up there til I figure it out or a workaround.

**Comment by paulmillr** [comment]
It's babel or some other build tool, which converts ** operator to Math.pow, and Math.pow can't be used with bigints. 

Adjust your browser target.

**Comment by danfinlay** [comment]
Sounds right, thanks! (Weird both browsers show the source-mapped original code, sure makes it hard to track down)
