### ISSUE TITLE
Compressed vs uncompressed `pubkey`

### ISSUE THREAD

**Issue by acolytec3** [paulmillr/noble-secp256k1#65]
Is there a simple way using the existing API + `utils` to convert a `pubkey` between the compressed and uncompressed forms?  I'm exploring switching the `discv5` library from the `bcrypto` secp256k1 implementation to this one but we need to be able to switch between compressed and uncompressed public keys without providing a private key in the middle if possible (`bcrypto` provides this method today).

**Comment by paulmillr** [comment]
secp.Point.fromHex(publicKey).toRawBytes(isCompressed);
