### ISSUE TITLE
p256

### ISSUE THREAD

**Issue by sublimator** [paulmillr/noble-secp256k1#7]
Would this work for p256 curve just by modifying the CURVE parameters ?

**Comment by paulmillr** [comment]
No.

Jacobian point (xyz) multiplication is specific to curve with a=0 (secp256k1). You will need to adjust JacobianPoint#double and #add methods.

See hyperelliptic.org for those formulas. They should be fairly straightforward to implement.

https://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html

**Comment by sublimator** [comment]
Thanks, was looking like that might be the case. 
Was thrown by this line: https://github.com/paulmillr/noble-secp256k1/blob/master/index.ts#L48
Nice article and lib! You thought of supporting some other curves for ecdsa ?

**Comment by paulmillr** [comment]
Right now i’m finalizing bls12-381, a nice pairing-friendly curve. It allows to verify 1000 signatures at a cost of verifying one signature, so it’s awesome.

It would be great to implement ed448, but haven’t had time to do this yet.

As for nist curves, they are implemented almost everywhere natively, so not seeing personal need for those.

**Comment by sublimator** [comment]
> they are implemented almost everywhere natively
Right, I was porting https://github.com/privacypass/challenge-bypass-extension from sjcl to elliptic/bn.js as a way of learning more about the privacypass [protocol](https://privacypass.github.io/protocol/) and ECC. 

Web crypto ("native" in the browser context) doesn't seem to expose any of the scalar multiplication primitives, only [signing/verifying operations](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/) etc.  

> not seeing personal need for those
Fair :)

**Comment by paulmillr** [comment]
Nice! It’s very useful extension. I hate those captchas & cloudflare. What operations are required in privacypass? I guess, ECDH?

**Comment by sublimator** [comment]
I've just been translating the protocol overview into code to get my head
around it:
https://github.com/coilhq/web-monetization-projects/blob/34f7c6feb3f6b264e64f64cd5264b98773b7e7bf/packages/coil-privacypass-elliptic/test/jest/scenarios.test.ts

It's WIP and haven't had anyone look at it yet, but you should be able to
see what operations it's using.
P * scalar multiplication for arbitrary P (not just G) and on ...

**Comment by sublimator** [comment]
https://github.com/privacypass/challenge-bypass-extension/blob/master/docs/HASH_TO_CURVE.md#affine-sswu-method

**Comment by paulmillr** [comment]
As for hash-to-curve, take a look at my bls12-381 repo. I have been working on applying the exact same standard to the curve for the last couple weeks. It can be reused for p256.

**Comment by sublimator** [comment]
Nice!

Ugh, so I realized elliptic p256 computations are like ~4x slower than
secp256k1

**Comment by paulmillr** [comment]
Do you have this working somewhere?

**Comment by sublimator** [comment]
No, I've move onto other things for the moment. The existing sjcl impl is working so it's hard to justify the time just at the moment. 

> Do you have this working somewhere?
Do you ?? :)

**Comment by sublimator** [comment]
Elliptic seems too slow with p256 curve ops so it's either improve that or modify this. Both would need auditing by people more knowledgeable than me.

**Comment by paulmillr** [comment]
p256 is available in https://github.com/paulmillr/noble-curves
