### ISSUE TITLE
Recovery ids other than 0 or 1?

### ISSUE THREAD

**Issue by scnale** [paulmillr/noble-secp256k1#72]
Hey, I was wondering if recovery IDs for ECDSA signatures other than 0 or 1 are supported. [Here](https://github.com/paulmillr/noble-secp256k1/blob/e74ade2caf21ea5e151d98ccae9c425d8beabb8d/index.ts#L471-L473), the recovery id is restricted to 0 or 1. However, the signing logic can generate recovery IDs 2 and 3 as I understand [here](https://github.com/paulmillr/noble-secp256k1/blob/e74ade2caf21ea5e151d98ccae9c425d8beabb8d/index.ts#L1005). Is there something I am missing in how these would be treated? 

From what little I've read, these other IDs are quite rare. I don't know if there are any readily available tests for these cases.

**Comment by paulmillr** [comment]
I think 2/3 only possible for CURVE.n <= R.x < CURVE.p, which almost never happens.
