### ISSUE TITLE
tweakUtils when the tweak is 0 throws

### ISSUE THREAD

**Issue by landabaso** [paulmillr/noble-secp256k1#73]
Hi @paulmillr ,

I am coming from [https://github.com/bitcoinjs/ecpair/issues/13](https://github.com/bitcoinjs/ecpair/issues/13).

I am using noble-secp256k1 with [ecpair](https://github.com/bitcoinjs/ecpair).

Since I still need tweakUtils' privatedAdd, ... I decided to copy the code on your tests to my wrapper as you suggest in Release Notes of 1.7.0.

Starting from version 2.1.0, ecpair runs additional tests on the embedded library.

There is [this one new test](https://github.com/bitcoinjs/ecpair/blob/master/src/testecc.js#L46) that does not pass:
```javascript
      ecc.privateAdd(
        h('0000000000000000000000000000000000000000000000000000000000000001'),
        h('0000000000000000000000000000000000000000000000000000000000000000'),
      ),
```

The reason is normalization of the tweak `const t = normalizePrivateKey(tweak);` throws because the tweak is zero.

I checked your tests for `tweakUtils`:

```javascript
    it('privateAdd()', () => {
      for (const vector of privates.valid.add) {
        const { a, b, expected } = vector;
        expect(secp.utils.bytesToHex(tweakUtils.privateAdd(a, b))).toBe(expected);
      }
```

This passes.

Then I saw you have other test vectors for `privateAdd` in `test/vectors/privates.json` that include the tweak = 0 case:

```javascript
    "privateAdd": [
      {
        "description": "1 + 0 == 1",
        "d": "0000000000000000000000000000000000000000000000000000000000000001",
        "tweak": "0000000000000000000000000000000000000000000000000000000000000000",
        "expected": "0000000000000000000000000000000000000000000000000000000000000001"
      }
```
But, for some reason, these vectors are not tested in your tests.

If I add them (see below), they do not pass (because the tweak = 0).

```javascript
      for (const vector of privates.valid.privateAdd) {
        const { d, tweak, expected } = vector;
        expect(secp.utils.bytesToHex(tweakUtils.privateAdd(d, tweak))).toBe(expected);
      }
    });
```
(the test above fails)

I know tweakUtils are not part of released noble-secp256k1 anymore but decided to let you know anyway in case you want to take a look to your tests.

**Comment by paulmillr** [comment]
Thanks. This should be adjusted then

**Comment by paulmillr** [comment]
On the other hand, the current behavior was made on purpose. Why would you add an all-zero private key? It's certainly invalid in ECDH context, and in some others.

**Comment by landabaso** [comment]
> On the other hand, the current behavior was made on purpose. Why would you add an all-zero private key? It's certainly invalid in ECDH context, and in some others.

I understand your point. It's more of an interoperability issue with [ecpair](https://github.com/bitcoinjs/ecpair). Not really a bug.
This issue concerns `tweakUtils` which aren't exposed anyway.

I copied and adjusted `tweakUtils` in my project with this little change. I just wanted to share this with you so you are aware.
BTW, in order to make noble-secp256k1 and ecpair work together, I also had to adjust tweakUtils functions [so that they throw](https://github.com/bitcoinjs/ecpair/issues/13#issuecomment-1261138105) when the computed private key is zero.

Feel free to close the issue as this is more of a comment than a bug.

**Comment by coolaj86** [comment]
@landabaso, I'm also trying to use this with HD wallet paths (to make a fully browser-compatible implementation).

What is "tweakUtils"? Whether I do a search for "tweakutils" on npm or "tweakutils secp256k1" on the web, I don't seem to get back any relevant results.

What `privateAdd()` function are you referring to? I don't see it in the docs or code here or the ecpair repo.

Could you post a link to your implementation?

**Comment by paulmillr** [comment]
For tweak utils, look into secp tests: they have the utils. It was part of the main pkg, then got removed because I think it has bad UX and it's just legacy of other libraries while here we have better primitives (Point).

For hdkey, take a look at scure/bip32.

**Comment by landabaso** [comment]
> Could you post a link to your implementation?

I hope it helps @coolaj86: https://github.com/bitcoinerlab/secp256k1

**Comment by coolaj86** [comment]
@landabaso I was able to get this to work with our APIs.

For anyone looking on, this is the code that's missing:

- `privateAdd` is known in other libraries as `privateKeyTweakAdd`
- `pointAddScalar` is known in other libraries as `publicKeyTweakAdd`

```js
  let tweakUtils = {
    /**
     * @param {Uint8Array} privateKey
     * @param {Uint8Array} tweak
     * @returns {Uint8Array} - a new (derivative) privateKey
     */
    privateAdd: function (privateKey, tweak) {
      const p = Secp256k1.utils._normalizePrivateKey(privateKey);
      const t = Secp256k1.utils._normalizePrivateKey(tweak);
      return Secp256k1.utils._bigintTo32Bytes(
        Secp256k1.utils.mod(p + t, Secp256k1.CURVE.n),
      );
    },

    /**
     * @param {Uint8Array} p
     * @param {Uint8Array} tweak
     * @param {Boolean} [isCompressed]
     * @returns {Uint8Array} - a new (derivative) publicKey
     */
    pointAddScalar: function (p, tweak, isCompressed) {
      const P = Secp256k1.Point.fromHex(p);
      const t = Secp256k1.utils._normalizePrivateKey(tweak);
      const Q = Secp256k1.Point.BASE.multiplyAndAddUnsafe(P, t, 1n);
      if (!Q) {
        throw new Error("Tweaked point at infinity");
      }
      return Q.toRawBytes(isCompressed);
    },
  };
```

This may need to be updated again for the upcoming major refactor.

**Comment by landabaso** [comment]
Yeah, you can get these functions from there.
BTW, there's a full implementation in the link I copied above as an npm package ready to use and heavily tested:

https://github.com/bitcoinerlab/secp256k1

Let me know if I can help you somehow.
