### ISSUE TITLE
Add low-S signature normalization

### ISSUE THREAD

**Issue by BasixKOR** [paulmillr/noble-secp256k1#74]
Something like `secp256k1_ecdsa_signature_normalize`. This would be helpful to read historic Bitcoin transactions or converting signatures to work with other applications which only accepts low-S signatures.

**Comment by paulmillr** [comment]
No plans for that: you could implement this in your code in a few lines. 

We provide the ability to parse high-S sigs, and the ability to change sig's S. The library functionality should be kept to bare minimum.
