### ISSUE TITLE
Is possible to detect Cloudflare workers  or add browser target?

### ISSUE THREAD

**Issue by aazf** [paulmillr/noble-secp256k1#77]
In Cloudflare Workers or some cloud functions them use WebCrypto instead crypto.
But when use npm install @noble/secp256k1, the default is use crypto not WebCrypto.

So is possible to detect the runtime or add  browser module compile?

https://github.com/panva/jose/blob/main/package.json#L95
https://github.com/panva/jose/blob/main/package.json#L120

Thanks

**Comment by paulmillr** [comment]
Of course. You can write a code that detects it and submit a pull request with tests.
