### ISSUE TITLE
options @param sign(msgHash, privateKey, opts?)

### ISSUE THREAD

**Issue by Chilly-169-table** [paulmillr/noble-secp256k1#83]
the sign API which has an optional options parameter takes in an object, one of which is {recovered : boolean} and whose  
value for the recovered key should be true instead of false as the description(README file) states what happens when true is given as the value for the key.
<img width="625" alt="Screenshot 2022-11-25 at 09 59 22" src="https://user-images.githubusercontent.com/38077723/203901640-fb411553-c800-4b60-b9bc-cbd7c928b924.png">

**Comment by paulmillr** [comment]
false is default argument value. boolean is possible types for it.
