### ISSUE TITLE
Suggestion: Use globalThis.crypto instead of node crypto for cross-platform compatibility.

### ISSUE THREAD

**Issue by cmdruid** [paulmillr/noble-secp256k1#98]
Hello. I would like to make a suggestion that I use for cross-compatibility between NodeJs and browser.

Using node crypto library without a bundler causes dependency problems for packages down-stream since they have to poly-fill for the node crypto API.

Nodejs offers a WebCrypto standard API that you can use like so:

```ts
import { webcrypto as crypto } from 'node:crypto'
```
However some bundlers still have issues with this (mainly rollup), so there is a cross-platform solution supported by nodejs by using `globalThis`:

```ts
const { crypto } = globalThis
```

This solution should work in both Node and the browser, without any package imports or requiring any polyfills.

I make this humble suggestion as I try to keep my dependencies minimal and stay away from polyfill packages which introduce their own problems. I hope this suggestion is helpful. Thank you for providing a wonderful library.

**Comment by paulmillr** [comment]
v2.0 (in pull req) already switched to globalThis.crypto.

We won't switch for v1 because node.js doesn't support it. Only nodejs v19 does, which is too new.

**Comment by cmdruid** [comment]
Cheers, I udnerstand. Thank you for responding!
